# Catppuccin Mocha, matches lazygit theme
gui:
  border: rounded
  theme:
    activeBorderColor:
      - "#89b4fa" # blue
      - bold
    inactiveBorderColor:
      - "#6c7086" # surface0
    selectedLineBgColor:
      - "#313244" # surface1
    optionsTextColor:
      - "#89b4fa" # blue
