# Oh My Zsh bez složky `custom`, aby se nepřekrýval s pluginy a theme
[".oh-my-zsh"]
type = "git-repo"
url = "https://github.com/ohmyzsh/ohmyzsh"
refreshPeriod = "168h"
exclude = ["custom/**"]

# Pluginy
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting"
refreshPeriod = "168h"
exact = true
clone.args = ["--quiet"]

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions"
refreshPeriod = "168h"
exact = true
clone.args = ["--quiet"]

[".oh-my-zsh/custom/plugins/fzf-tab"]
type = "git-repo"
url = "https://github.com/Aloxaf/fzf-tab"
refreshPeriod = "168h"
exact = true
clone.args = ["--quiet"]

[".oh-my-zsh/custom/plugins/you-should-use"]
type = "git-repo"
url = "https://github.com/MichaelAquilina/zsh-you-should-use"
refreshPeriod = "168h"
exact = true
clone.args = ["--quiet"]

# Téma
[".oh-my-zsh/custom/themes/powerlevel10k"]
type = "git-repo"
url = "https://github.com/romkatv/powerlevel10k"
refreshPeriod = "168h"
exact = true
clone.args = ["--quiet"]

# Tmux TPM plugin
[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"
refreshPeriod = "1h"
