return {
	{
		"folke/which-key.nvim",
		opts = {
			spec = {
				{ "<leader>b", desc = "Buffer select", icon = "" },
				{ "<leader>bb", desc = "Pick buffers", icon = "﬘" },
				{ "<leader>bd", desc = "Close buffer", icon = "" },
				{ "<leader>bD", desc = "Delete all buffers", icon = "" },
				{ "<leader>bn", desc = "Next buffer", icon = "" },
				{ "<leader>bp", desc = "Previous buffer", icon = "" },
				{ "<leader>co", icon = { icon = "", color = "purple" } },
				{ "<leader>bP", desc = "Pin buffer" },
				{ "<leader>cp", desc = "Copy path" },
				{ "<leader>d", desc = "Diffview", icon = "" },
				{ "<leader>e", desc = "Explorer", icon = "" },
				{ "<leader>eb", desc = "Buffers", icon = "" },
				{ "<leader>ee", desc = "Open Explorer", icon = "" },
				{ "<leader>eg", desc = "Git Status", icon = "" },
				{ "<leader>et", desc = "Toggle Explorer", icon = "" },
				{ "<leader>gh", desc = "GitSigns", icon = { icon = "󰞁", color = "red" } },
				{ "<leader>ghb", icon = "󰱩" },
				{ "<leader>ghp", icon = "" },
				{ "<leader>ghr", icon = { icon = "󰆴", color = "red" } },
				{ "<leader>ghs", icon = { icon = "󰥝", color = "orange" } },
				{ "<leader>n", desc = "npm / package-info", icon = "" },
				{ "<leader>nd", desc = "Delete dependency" },
				{ "<leader>ni", desc = "Install dependency" },
				{ "<leader>np", desc = "Change dep version" },
				{ "<leader>ns", desc = "Show dep versions" },
				{ "<leader>nt", desc = "Toggle dep versions" },
				{ "<leader>nu", desc = "Update dependency" },
				{ "<leader>p", desc = "Explorer/paste" },
				{ "<leader>pv", desc = "Explorer", icon = "" },
				{ "<leader>r", icon = { icon = "󰛔" } },
				{ "<leader>ts", icon = "󱜹" },
				{ "<leader>x", desc = "Trouble / diagnostics", icon = "󰔫" },
				{ "<leader>xt", desc = "Todo (Trouble)" },
				{ "<leader>u", icon = "" },
			},
		},
	},
	{ "folke/neoconf.nvim", cmd = "Neoconf" },
}
